//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRentalHouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistory
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public int PositionId { get; set; }
        public string ReasonForTransfer { get; set; }
        public System.DateTime DateOfOrder { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
