//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRentalHouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.EmploymentHistories = new HashSet<EmploymentHistory>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Building { get; set; }
        public int StreetId { get; set; }
        public string Apartment { get; set; }
        public int PositionId { get; set; }
        public string Gender { get; set; }
        public decimal SalaryIncrease { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool IsDismissed { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual Position Position { get; set; }
        public virtual Street Street { get; set; }
    }
}
