//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRentalHouse.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockKeepingUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockKeepingUnit()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public int ManufacturerId { get; set; }
        public int DeviceId { get; set; }
        public decimal RentalPrice { get; set; }
        public decimal DevicePrice { get; set; }
        public bool IsInStock { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
